### PR TITLE
Fix Android serial support

### LINKED ISSUE #1334: Serial only works periodically on Android
Serial may not be functioning completely on Android. This has been an issue for a while and supposedly did not happen before. Sometimes only works after rebooting device or app, only functioning once. Needs further testing and research.

### PR DESCRIPTION
**Pull request by ButterscotchV**
Fixes the major issues with serial on Android:
- Uses Android USB events to enumerate serial devices rather than polling
- Clears permission request on device removal or permission approval
  - Subsequentent connections now re-request instead of blocking due to the previous request
- Closes serial port on disconnect
  - No longer hangs after removal or on reconnection

Fixes #1334

### CODE REVIEW

**Review by ImUrX — APPROVED** [review]
looks great :3

File: server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt [hunk 1]
```diff
@@ -43,12 +44,11 @@ class AndroidSerialHandler(val activity: AppCompatActivity) :
 	private var usbIoManager: SerialInputOutputManager? = null
 
 	private val listeners: MutableList<SerialListener> = CopyOnWriteArrayList()
-	private val getDevicesTimer = Timer("GetDevicesTimer")
-	private var watchingNewDevices = false
 	private var lastKnownPorts = setOf<SerialPortWrapper>()
 	private val manager = activity.getSystemService(Context.USB_SERVICE) as UsbManager
 	private var currentPort: SerialPortWrapper? = null
 	private var requestingPermission: String = ""
+	private var readBuffer: StringBuilder = StringBuilder(4096)
```
Comment (ImUrX) [inline server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt]:
```suggestion
	private var readBuffer: StringBuilder = StringBuilder(1024)
```
i think 1024 chars is enough?

File: server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt [hunk 2]
```diff
@@ -251,14 +290,21 @@ class AndroidSerialHandler(val activity: AppCompatActivity) :
...
 	override fun onNewData(data: ByteArray?) {
 		if (data != null) {
-			val s = StandardCharsets.UTF_8.decode(ByteBuffer.wrap(data)).toString()
-			addLog(s, false)
+			// Collect serial in a buffer until newline (or character limit)
+			// This is somewhat of a workaround for Android serial buffer being smaller
+			//  than on desktop, so we don't read full lines and it causes parsing issues
+			readBuffer.append(StandardCharsets.UTF_8.decode(ByteBuffer.wrap(data)))
+
+			if (readBuffer.contains('\n') || readBuffer.length >= 4096) {
```
Comment (ImUrX) [inline server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt]:
```suggestion
			if (readBuffer.contains('\n') || readBuffer.length >= 1024) {
```

File: server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt (hunk 1 above)
Comment (ButterscotchV) [reply server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt]: I originally set it to 512, but changed it to 4096 to match the desktop implementation. I could change it to 1024 though, maybe it would be better as that.

Comment (ImUrX) [reply server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt]: sounds better to have it smol for android devices with not many resources

Comment (ButterscotchV) [reply server/android/src/main/java/dev/slimevr/android/serial/AndroidSerialHandler.kt]: Using 1024 now

**Review by Eirenliel — APPROVED** [review]
