### PR TITLE
Fix race condition in DataFeedHandler::sendDataFeedUpdate

### LINKED ISSUE #1620: Race condition in `DataFeedHandler::sendDataFeedUpdate`
When the GUI starts up and sends the `StartDataFeed` packet, `sendDataFeedUpdate` might run while `onStartDataFeed` is setting up the `ConnectionContext`'s `dataFeedConfigList` and `dataFeedTimers` lists, which may result in a server crash.
```
19:10:11 [INFO] [WebSocketAPI] New connection from: 0:0:0:0:0:0:0:1
19:10:11 [SEVERE] Exception in thread "VRServer" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
19:10:11 [SEVERE]         at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
19:10:11 [SEVERE]         at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
19:10:11 [SEVERE]         at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
19:10:11 [SEVERE]         at java.base/java.util.Objects.checkIndex(Objects.java:361)
19:10:11 [SEVERE]         at java.base/java.util.ArrayList.get(ArrayList.java:427)
19:10:11 [SEVERE]         at dev.slimevr.protocol.datafeed.DataFeedHandler.lambda$sendDataFeedUpdate$0(DataFeedHandler.java:129)
19:10:11 [SEVERE]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
19:10:11 [SEVERE]         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
19:10:11 [SEVERE]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
19:10:11 [SEVERE]         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
19:10:11 [SEVERE]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
19:10:11 [SEVERE]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
19:10:11 [SEVERE]         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
19:10:11 [SEVERE]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
19:10:11 [SEVERE]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
19:10:11 [SEVERE]         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
19:10:11 [SEVERE]         at dev.slimevr.protocol.datafeed.DataFeedHandler.lambda$sendDataFeedUpdate$1(DataFeedHandler.java:121)
19:10:11 [SEVERE]         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
19:10:11 [SEVERE]         at dev.slimevr.protocol.datafeed.DataFeedHandler.sendDataFeedUpdate(DataFeedHandler.java:121)
19:10:11 [SEVERE]         at dev.slimevr.VRServer.run(VRServer.kt:233)
```
```
19:22:23 [INFO] [WebSocketAPI] New connection from: 0:0:0:0:0:0:0:1
19:22:24 [INFO] [WebSocketAPI] Disconnected: 0:0:0:0:0:0:0:1, (1006) Connection reset by peer. Remote: false
19:22:25 [INFO] [WebSocketAPI] New connection from: 0:0:0:0:0:0:0:1
19:22:25 [INFO] [WebSocketAPI] Disconnected: 0:0:0:0:0:0:0:1, (1006) Connection reset. Remote: false
19:22:26 [INFO] [WebSocketAPI] New connection from: 0:0:0:0:0:0:0:1
19:22:26 [INFO] [WebSocketAPI] Disconnected: 0:0:0:0:0:0:0:1, (1006) . Remote: true
19:22:27 [INFO] [WebSocketAPI] New connection from: 0:0:0:0:0:0:0:1
19:22:27 [SEVERE] Exception in thread "VRServer" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
19:22:27 [SEVERE]         at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
19:22:27 [SEVERE]         at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
19:22:27 [SEVERE]         at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
19:22:27 [SEVERE]         at java.base/java.util.Objects.checkIndex(Objects.java:361)
19:22:27 [SEVERE]         at java.base/java.util.ArrayList.get(ArrayList.java:427)
19:22:27 [SEVERE]         at dev.slimevr.protocol.datafeed.DataFeedHandler.lambda$sendDataFeedUpdate$0(DataFeedHandler.java:129)
```

### PR DESCRIPTION
**Pull request by ImSapphire**
Fixes #1620

### CODE REVIEW

File: server/core/src/main/java/dev/slimevr/protocol/datafeed/DataFeedHandler.java [hunk 1]
```diff
@@ -32,14 +33,16 @@ private void onStartDataFeed(GenericConnection conn, DataFeedMessageHeader heade
...
-			DataFeedConfigT config = req.dataFeeds(i).unpack();
-			conn.getContext().getDataFeedConfigList().add(config);
-			conn.getContext().getDataFeedTimers().add(System.currentTimeMillis());
+		synchronized (conn.getContext().getDataFeedList()) {
+			conn.getContext().clearDataFeeds();
+			for (int i = 0; i < dataFeeds; i++) {
+				// Using the object api here because we need to copy from the
+				// buffer
+				// anyway so
+				// let's do it from here and send the reference to an arraylist
```
Comment (ButterscotchV) [inline server/core/src/main/java/dev/slimevr/protocol/datafeed/DataFeedHandler.java]: This comment is a lil' fucked by formatting

File: server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java [hunk 2]
```diff
@@ -23,17 +15,12 @@ public class ConnectionContext {
...
-		return dataFeedTimers;
+	public List<DataFeed> getDataFeedList() {
+		return dataFeedList;
 	}
 
 	public void clearDataFeeds() {
-		this.dataFeedConfigList.clear();
-		this.dataFeedTimers.clear();
+		this.dataFeedList.clear();
 	}
```
Comment (ButterscotchV) [inline server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java]: This should probably also be synchronized with `dataFeedList`?

**Review by ButterscotchV — COMMENTED** [review]
I hate that this is in Java =w= we should probably make an effort to finish conversion of everything to Kotlin. Anyways, just two small things, looks fine though.

File: server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java (hunk 2 above)
Comment (ImSapphire) [reply server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java]: It's only called in `onStartDataFeed` from in a `synchronized` block, so I think it's fine

Comment (ImSapphire) [reply server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java]: This function could also just be inlined, since it's a one-liner now

File: server/core/src/main/java/dev/slimevr/protocol/datafeed/DataFeedHandler.java (hunk 1 above)
Comment (ImSapphire) [reply server/core/src/main/java/dev/slimevr/protocol/datafeed/DataFeedHandler.java]: Reformatted the comment a bit

File: server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java (hunk 2 above)
Comment (ButterscotchV) [reply server/core/src/main/java/dev/slimevr/protocol/ConnectionContext.java]: > This function could also just be inlined, since it's a one-liner now

ty, this solution looks better

**Review by ButterscotchV — APPROVED** [review]

**Comment by loucass003** [comment]
yes waiting for release of 0.17
